hmcts/probate-caveats-frontend

.gitignore
app/journeys/probate-caveats.js
app/resources/en/translation/applicant/email.json
app/steps/ui/applicant/email/index.js
app/steps/ui/applicant/email/schema.json
app/steps/ui/applicant/email/template.html
test/component/applicant/testApplicantEmail.js
test/component/applicant/testApplicantName.js
test/end-to-end/pages/applicant/email.js
test/end-to-end/pages/steps.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testApplicantEmail.js

Addition of application email page

Pro 4137 applicant email

---

app/config.js
app/journeys/probate-caveats.js
app/resources/en/translation/applicant/address.json
app/routes.js
app/steps/ui/applicant/address/index.js
app/steps/ui/applicant/address/schema.json
app/steps/ui/applicant/address/template.html
test/accessibility/a11yTest.js
test/component/applicant/testAddress.js
test/component/applicant/testApplicantEmail.js
test/end-to-end/pages/applicant/address.js
test/end-to-end/pages/steps.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testAddressLookup.js
test/unit/testAddressLookupService.js
test/unit/testAddressStep.js
test/unit/testApplicantAddress.js

Add applicant address to caveat journey

Pro 4146 applicant address

---

app/journeys/probate-caveats.js
app/resources/en/translation/deceased/name.json
app/steps/ui/deceased/name/index.js
app/steps/ui/deceased/name/schema.json
app/steps/ui/deceased/name/template.html
test/component/applicant/testAddress.js
test/component/deceased/testName.js
test/end-to-end/pages/deceased/name.js
test/end-to-end/pages/steps.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testDeceasedName.js

add deceased name to the caveat journey

PRO-4147: deceased name plus tests

---

app/journeys/probate-caveats.js
app/resources/en/translation/deceased/dod.json
app/steps/ui/deceased/dod/index.js
app/steps/ui/deceased/dod/schema.json
app/steps/ui/deceased/dod/template.html
test/component/deceased/testDoD.js
test/component/deceased/testName.js
test/end-to-end/pages/deceased/dod.js
test/end-to-end/pages/steps.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testDeceasedDod.js

add deceased date of death to caveat journey

Pro 4149 deceased date of death

---

app/journeys/probate-caveats.js
app/resources/en/translation/deceased/dob.json
app/resources/en/translation/deceased/dobknown.json
app/steps/ui/deceased/dob/index.js
app/steps/ui/deceased/dob/schema.json
app/steps/ui/deceased/dob/template.html
app/steps/ui/deceased/dobknown/index.js
app/steps/ui/deceased/dobknown/schema.json
app/steps/ui/deceased/dobknown/template.html
app/wrappers/Deceased.js
test/component/deceased/testDoB.js
test/component/deceased/testDoD.js
test/component/deceased/testDoDKnown.js
test/end-to-end/codecept.conf.js
test/end-to-end/pages/deceased/dob.js
test/end-to-end/pages/deceased/dobknown.js
test/end-to-end/pages/steps.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testDeceasedDob.js
test/unit/testDeceasedDobKnown.js

add deceased date of birth to caveat journey

PRO-4150: Deceased DoB

---

infrastructure/saat.tfvars

https://tools.hmcts.net/jira/browse/PRO-4246

Pro 4246 create saat

---

infrastructure/aat.tfvars

https://tools.hmcts.net/jira/browse/PRO-4245

Pro 4245 create aat env

---

app/journeys/probate-caveats.js
app/resources/en/translation/addAlias.json
app/resources/en/translation/deceased/alias.json
app/resources/en/translation/deceased/otherNames.json
app/resources/en/translation/removeAlias.json
app/steps/action/addAlias/index.js
app/steps/action/addAlias/schema.json
app/steps/action/removeAlias/index.js
app/steps/action/removeAlias/schema.json
app/steps/ui/deceased/alias/index.js
app/steps/ui/deceased/alias/schema.json
app/steps/ui/deceased/alias/template.html
app/steps/ui/deceased/dob/template.html
app/steps/ui/deceased/otherNames/index.js
app/steps/ui/deceased/otherNames/schema.json
app/steps/ui/deceased/otherNames/template.html
test/component/deceased/testAlias.js
test/component/deceased/testDoDKnown.js
test/component/deceased/testOtherNames.js
test/end-to-end/pages/deceased/alias.js
test/end-to-end/pages/deceased/otherNames.js
test/end-to-end/pages/steps.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testAddAlias.js
test/unit/testDeceasedAlias.js
test/unit/testOtherNames.js
test/unit/testRemoveAlias.js

add deceased alias to the caveat journey

PRO-4174: Deceased Alias

---

app/journeys/probate-caveats.js
app/resources/en/translation/deceased/address.json
app/resources/en/translation/deceased/addressknown.json
app/steps/ui/deceased/address/index.js
app/steps/ui/deceased/address/schema.json
app/steps/ui/deceased/address/template.html
app/steps/ui/deceased/addressknown/index.js
app/steps/ui/deceased/addressknown/schema.json
app/steps/ui/deceased/addressknown/template.html
test/component/deceased/testAddress.js
test/component/deceased/testAddressKnown.js
test/component/deceased/testAlias.js
test/component/deceased/testOtherNames.js
test/end-to-end/pages/deceased/address.js
test/end-to-end/pages/deceased/addressknown.js
test/end-to-end/pages/steps.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testDeceasedAddress.js
test/unit/testDeceasedAddressKnown.js

add deceased address to the caveat journey

PRO-4148: Deceased Address

---

Dockerfile

Resolves CNP-1103
Hello, this PR adds the following enhancements:
improve the ordering of the docker image build layer
prepare for future ACR cache optimisations.
This is part of a general pipelines optimisations initiative and should not impact the current builds.

cnp1103-Add Dockerfile optimisations

---

.dockerignore
Dockerfile
acb.tpl.yaml

https://tools.hmcts.net/jira/browse/CNP-1131
This PR leverages on layers re-use to reduce the the docker image build time in CI.
It also introduces [base nodeJS images](https://github.com/hmcts/cnp-node-base) as well as the `hmcts` user, added for security compliance.

Use ACR cache optimisation in pipeline

---

infrastructure/sprod.tfvars

https://tools.hmcts.net/jira/browse/PRO-4247

Pro 4247 create sprod env

---

Jenkinsfile_CNP
charts/probate-caveats-fe/values.template.yaml
infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PRO-4857
```
[ ] Yes
[ ] No
```

Pro 4857 caveats add secret envs

---

infrastructure/main.tf

update caveat_user name and password in main.tf

---

infrastructure/variables.tf

remove caveat_user name and password vars from variable.tf

---

app/core/runners/UIStepRunner.js
charts/probate-caveats-fe/values.template.yaml

Update UIStepRunner to pass hostname on handlepost
[ ] Yes
[ ] No
```

Update UIStepRunner to pass hostname on handlepost

---

infrastructure/main.tf

change main.tf to create  caveat_user_email variable
[ ] Yes
[x ] No
```

PRO-4933: change main.tf to create  caveat_user_email variable

---

infrastructure/variables.tf

update to variables.tf to use caveat_user_name
[ ] Yes
[ x] No
```

Pro 4933 update to variables.tf to use caveat_user_name

---

infrastructure/main.tf
infrastructure/variables.tf

change main.tf to create caveat_user_name correctly
[ ] Yes
[ x] No
```

PRO-4933: change main.tf to create caveat_user_name correctly

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
infrastructure/sprod.tfvars

update idam to correct version
[ ] Yes
[ x] No
```

PRO-4933: update idam to correct version

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

change payment_create_url
[ ] Yes
[x ] No
```

PRO-4933: change payment_create_url

---

infrastructure/aat.tfvars
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
infrastructure/sprod.tfvars

change https to hhtp for orchestration service
[ ] Yes
[ x] No
```

PRO-4933: change https to http for orchestration service

---

app/components/pdf-services.js
app/components/services.js
app/components/submit-data.js
app/core/runners/RedirectRunner.js
app/routes.js
package.json
test/data/unit/fullcaveatform.json
test/data/unit/minimalcaveatform.json
test/unit/testSubmitData.js

change caveat submission identifier
[ ] Yes
[x ] No
```

Pro 5001 change caveat submission identifier

---

Dockerfile
app/components/security.js
app/middleware/lockPaymentAttempt.js
app/routes.js
app/steps/ui/payment/breakdown/index.js
app/steps/ui/payment/status/index.js
test/component/payment/testPaymentBreakdown.js
test/component/payment/testPaymentStatus.js
test/unit/testLockPaymentAttempt.js
test/unit/testPaymentBreakdown.js

PRO 4992 Stop duplicate caveat submissions on double click
[ ] Yes
[ X] No
```

PRO 4992 Stop duplicate caveat submissions on double click

---

Jenkinsfile_CNP

unbreaking prod build

---

infrastructure/prod.tfvars

Adding the vars to prod.tfvars
```
[ ] Yes
[x ] No
```

Adding vars to prod.tfvars

---

infrastructure/aat.tfvars

change to sidam url
[ ] Yes
[x ] No
```

PRO-5085: change to sidam url

---

charts/probate-caveats-fe/values.template.yaml

chart to sidam

---

app/steps/ui/deceased/alias/index.js

Ensure that alias names are displyed and reset correctly
[ ] Yes
[x ] No
```

PRO-4984: ensure that alias names are displyed and reset correctly

---

app/resources/en/translation/startpage.json

https://tools.hmcts.net/jira/browse/PRO-5027
Amend copy on Start Eligibility page
```
[ ] Yes
[X] No
```

PRO-5027: Amend copy on Start Eligibility page

---

app.js
app/config.js

set secure flag on cookie
[ ] Yes
[x ] No
```

Pro 5057 set secure flag on cookie

---

infrastructure/prod.tfvars

Adding external hostname

---

app/assets/sass/application-common.scss
app/resources/en/translation/startpage.json
app/steps/ui/startpage/template.html

https://tools.hmcts.net/jira/browse/PRO-5053
Add 2 paragraphs to Start Page
```
[ ] Yes
[X] No
```

PRO-5053: Add 2 paragraphs to Start Page

---

test/end-to-end/codecept.conf.js

chrome browser show modified

---

app.js
app/components/logger.js
app/components/security.js
app/components/services.js
app/middleware/lockPaymentAttempt.js
app/steps/ui/payment/breakdown/index.js
app/steps/ui/payment/status/index.js
test/end-to-end/codecept.conf.js
test/unit/testLockPaymentAttempt.js

improve caveat logging
[ ] Yes
[x ] No
```

PRO-5007: improve caveat logging

---

Jenkinsfile_CNP

Adding SIDAM curl

---

app/config.js
app/resources/en/translation/common.json
app/views/includes/help_details.html
test/component/common/testHelpBlockContent.js

https://tools.hmcts.net/jira/browse/PRO-5106
Also make some optimisations...
```
[ ] Yes
[X] No
```

PRO-5106: Change email address on AD block

---

.gitignore
app/core/steps/Step.js
app/steps/ui/startpage/template.html
app/steps/ui/summary/template.html
app/views/widgets/checkanswer.html
sonar-project.properties

Correct minor sonar issues
[ ] Yes
[ ] No
```

PRO-5099: Correct minor sonar issues

---

Jenkinsfile_CNP

break prod deploy

---

app/components/api-utils.js
app/components/logger.js
app/components/pdf-services.js
app/components/security.js
app/components/services.js
app/routes.js
app/steps/ui/payment/breakdown/index.js
app/steps/ui/payment/status/index.js
test/unit/testSecurity.js

New improved logging
[ ] Yes
[ x] No
```

PRO-5007: New improved logging

---

test/end-to-end/helpers/PuppeteerHelper.js
test/end-to-end/paths/standardExecutionPath.js

Updated E2E tests and catch block for Async

---

app/steps/ui/summary/includes/about-you.njk
app/steps/ui/summary/includes/deceased.njk
app/steps/ui/summary/template.html
app/views/widgets/checkanswer.html
test/unit/testCheckAnswersSummaryJSONObjectBuilder.js

https://tools.hmcts.net/jira/browse/PRO-5121
Change dl, div and dt/dd to table, tr and th/td
```
[ ] Yes
[X] No
```

PRO-5121: Change dl, div and dt/dd to table, tr and th/td

---

app.js
package.json

add anti-caching directives and increase smoke test timeout
```
[ ] Yes
[ x] No
```

PRO-5063: add anti-caching directives and increase smoke test timeout

---

Jenkinsfile_CNP

removing break from prod pipeline
[x ] No
```

unbreak pipeline

---

Jenkinsfile_CNP
charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/requirements.yaml
charts/probate-caveats-fe/values.template.yaml

add sidam helm chart for whitelisting

---

app/components/security.js

additional logging
```
[ ] Yes
[ ] No
```

PRO-5187: additional logging

---

app/components/security.js

remove additional logging for discovering hostname
```
[ ] Yes
[ ] No
```

PRO-5187: remove additional logging for discovering hostname

---

app/routes.js

PRO-4946: add basePath to start page route
```
[ ] Yes
[ ] No
```

PRO-4946: add basePath to start page route

---

app/config.js

PRO-4946: add basePath to whitelisted pages
```
[ ] Yes
[ ] No
```

PRO-4946: add basePath to whitelisted pages

---

app/config.js

PRO-4964: Wrap whitelist pages with app_base_path
```
[ ] Yes
[ x] No
```

PRO-4964: Wrap whitelist pages with app_base_path

---

app/components/security.js
app/config.js
charts/probate-caveats-fe/values.aat.template.yaml
charts/probate-caveats-fe/values.template.yaml
infrastructure/main.tf

use internal url for idam callback

---

app/components/services.js

use_idam_internal, clog hostname
```
[ ] Yes
[x ] No
```

use_idam_internal, clog hostname

---

app/components/services.js
app/config.js
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

Use external url for payment status

---

infrastructure/main.tf

fix main.tf var

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars

fix platform spelling

---

test/config.js
test/end-to-end/pages/applicant/name.js
test/end-to-end/pages/deceased/othernames.js
test/end-to-end/paths/standardExecutionPath.js

Fixed e2e tests

---

app.js
test/end-to-end/pages/applicant/name.js

Remove console.log()

---

test/end-to-end/codecept.conf.js

PRO-4869:  Refactor test config files

---

charts/probate-caveats-fe/values.preview.template.yaml
test/end-to-end/paths/standardExecutionPath.js

tidy too many postgres.

---

Jenkinsfile_CNP
app/components/services.js
app/components/string-utils.js
app/config.js
app/steps/action/addressLookup/index.js
app/views/widgets/addresslookup.html
charts/probate-caveats-fe/values.yaml
package.json
test/component/applicant/testAddress.js
test/config.js
test/data/find-address.json
test/unit/testAddressLookup.js
test/unit/testAddressLookupService.js
test/unit/testStringUtils.js
yarn.lock

https://tools.hmcts.net/jira/browse/PRO-1701
Update to change to new postcode api.
```
[ ] Yes
[x] No
```

Pro 1701 new address picker api

---

infrastructure/main.tf

change test secret2

---

app/utils/CheckAnswersSummaryJSONObjectBuilder.js
test/unit/testCheckAnswersSummaryJSONObjectBuilder.js

PRO-5747: update cheerio text command
```
[ ] Yes
[ ] No
```

PRO-5747: update cheerio text command

---

app/views/widgets/addresslookup.html

https://tools.hmcts.net/jira/browse/PRO-5831
Fix bug with addresses containing single quotes
```
[ ] Yes
[X] No
```

PRO-5831: Fix bug with addresses containing single quotes

---

charts/probate-caveats-fe/requirements.yaml
charts/probate-caveats-fe/values.yaml

update docker repo

---

app/components/services.js
app/config.js
app/middleware/lookupFees.js
app/middleware/lookupPaymentFees.js
app/paymentFees.js
app/routes.js
app/steps/ui/payment/breakdown/index.js
app/utils/FeesLookup.js
charts/probate-caveats-fe/values.preview.template.yaml
charts/probate-caveats-fe/values.yaml
infrastructure/main.tf
test/accessibility/a11yTest.js
test/component/payment/testPaymentBreakdown.js
test/data/unit/paymentfeeslookup-response.json
test/unit/testFeesLookup.js
test/unit/testFeesLookupService.js
test/unit/testLookupPaymentFees.js
test/unit/testPaymentBreakdown.js

https://tools.hmcts.net/jira/browse/PRO-4763
Integrate caveats with fees register. 
```
[ ] Yes
[x] No
```

Pro 4763 caveats fees register

---

app/resources/en/translation/common.json
app/steps/ui/thankyou/template.html

Add noreferrer to survey links
```
[ ] Yes
[X] No
```

Add noreferrer to survey links

---

app/config.js
app/featureToggles.js
app/views/includes/help_details.html
app/views/includes/scripts.html
test/service-stubs/feature-toggles.js
test/unit/testFeatureToggle.js

https://tools.hmcts.net/jira/browse/PRO-6048
Code cleanup: remove Webchat feature toggle
```
[ ] Yes
[X] No
```

PRO-6048: Remove Webchat feature toggle

---

Jenkinsfile_CNP
infrastructure/main.tf

added break to prod

---

app/views/includes/scripts.html
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PRO-6428
Enable Google Analytics tracking
```
[ ] Yes
[X] No
```

PRO-6428: Added Enable Tracking

---

app/steps/ui/applicant/address/template.html
app/steps/ui/deceased/address/template.html
app/views/includes/two_thirds_form.html
app/views/widgets/addresslookup.html

https://tools.hmcts.net/jira/browse/PRO-5061
Turn off autocomplete on input fields
```
[ ] Yes
[X] No
```

PRO-5061: Turn off autocomplete

---

app.js

https://tools.hmcts.net/jira/browse/PRO-6510
Show content on error pages
```
[ ] Yes
[X] No
```

PRO-6510: Have content available on error pages

---

app/steps/ui/deceased/alias/template.html
app/steps/ui/shutterpage/template.html
app/views/errors/403.html
app/views/errors/404.html
app/views/errors/500.html

https://tools.hmcts.net/jira/browse/PRO-5862
Static survey links on error pages
```
[ ] Yes
[X] No
```

PRO-5862: Static survey links on error pages

---

charts/probate-caveats-fe/requirements.yaml
charts/probate-caveats-fe/values.preview.template.yaml

Added fix for feature toggle pr

---

app/config.js
app/resources/en/translation/common.json
app/steps/ui/payment/status/index.js
app/views/includes/help_details.html
app/views/includes/scripts.html
test/config.js

https://tools.hmcts.net/jira/browse/PRO-6776
Change helpline and webchat opening hours
```
[ ] Yes
[X] No
```

PRO-6776: Change helpline and webchat opening hours

---

app/resources/cy/translation/common.json

WLA-18: Add English language toggle

---

app/config.js
app/resources/cy/translation/language.json
app/resources/en/translation/language.json
app/routes.js
app/steps/ui/startapply/template.html
app/steps/ui/summary/includes/deceased.njk
app/utils/FormatUrl.js

Wla 18 gop language question

---

app/routes.js

WLA-18: Fix routing

---

app/config.js
app/routes.js

WLA-18: Remove applicant name from whitelisted pages

---

Jenkinsfile_CNP
web.config

PRO-5062:Information Disclosure in Response Headers

---

Jenkinsfile_CNP

Release to prod

---

app/steps/ui/summary/includes/about-you.njk
app/steps/ui/summary/index.js

https://tools.hmcts.net/jira/browse/WLA-296
Fix link to Bilingual question by passing the basePath
```
[ ] Yes
[X] No
```

[DO NOT MERGE] WLA-296: Fix link to Bilingual question

---

app/components/submit-data.js
app/steps/ui/deceased/alias/index.js
app/steps/ui/deceased/alias/template.html
app/steps/ui/deceased/dobknown/index.js
app/steps/ui/deceased/dobknown/schema.json
app/steps/ui/deceased/dobknown/template.html
app/steps/ui/shutterpage/template.html
app/steps/ui/startapply/template.html
app/steps/ui/static/contact/template.html
app/steps/ui/static/cookies/template.html
app/steps/ui/static/privacy/template.html
app/steps/ui/static/terms/template.html
app/steps/ui/summary/includes/deceased.njk
app/steps/ui/thankyou/template.html
app/views/errors/403.html
app/views/errors/404.html
app/views/errors/500.html
app/views/includes/layout.html
app/views/includes/scripts.html
app/views/widgets/addresslookup.html
app/wrappers/Deceased.js
test/component/deceased/testAlias.js
test/component/deceased/testDoDKnown.js
test/component/summary/testDeceasedSection.js
test/end-to-end/pages/deceased/alias.js
test/end-to-end/pages/deceased/dobknown.js
test/end-to-end/paths/standardExecutionPath.js
test/unit/testDeceasedAlias.js
test/unit/testDeceasedDobKnown.js
test/unit/testSubmitData.js

https://tools.hmcts.net/jira/browse/WLA-1
Store answer keys instead of answer values
```
[ ] Yes
[X] No
```

[DO NOT MERGE] WLA-1: Store keys as answers (Caveats)

---

app/components/payment-data.js

Pass empty flag is language is EN

---

app/components/payment-data.js

PRO-1234: pass Sonarcloud

---

app/components/payment-data.js

PRO-1234: Revert

---

test/unit/components/testPaymentData.js

Add unit tests for PaymentData

---

Jenkinsfile_CNP

PRO-1234: unbreak pipeline

---

app/core/steps/ValidationStep.js
app/journeys/probate-caveats.js
app/steps/ui/applicant/address/index.js
app/steps/ui/applicant/email/index.js
app/steps/ui/applicant/name/index.js
app/steps/ui/deceased/address/index.js
app/steps/ui/deceased/alias/index.js
app/steps/ui/deceased/dob/index.js
app/steps/ui/deceased/dobknown/index.js
app/steps/ui/deceased/dod/index.js
app/steps/ui/deceased/name/index.js
app/steps/ui/deceased/othernames/index.js
app/steps/ui/payment/breakdown/index.js
app/steps/ui/payment/status/index.js
app/steps/ui/startapply/index.js
app/steps/ui/startapply/template.html
app/steps/ui/summary/includes/about-you.njk
app/steps/ui/summary/index.js
test/component/deceased/testAddress.js
test/unit/testApplicantAddress.js
test/unit/testApplicantEmail.js
test/unit/testApplicantName.js
test/unit/testDeceasedAddress.js
test/unit/testDeceasedAlias.js
test/unit/testDeceasedDobKnown.js
test/unit/testDeceasedName.js
test/unit/testOtherNames.js
test/unit/testPaymentBreakdown.js
test/unit/testPaymentStatus.js
test/unit/testSummary.js

N/A
Move Language question
```
[ ] Yes
[X] No
```

Move Language question

---

Jenkinsfile_CNP

Remove enableDockerBuild() from Jenkinsfile_CNP

---

app/config.js
app/utils/FeesLookup.js

https://tools.hmcts.net/jira/browse/PRO-7062
Update demo environment to use new fee keywords
```
[ ] Yes
[x] No
```

Pro 7062 update fees code

---

app.js
config/custom-environment-variables.yaml
config/default.yaml

https://tools.hmcts.net/jira/browse/PRO-7155
Generate CSRF Token correctly
```
[ ] Yes
[X] No
```

PRO-7155: Generate CSRF Token correctly

---

charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.preview.template.yaml
charts/probate-caveats-fe/values.yaml

fixing port

---

infrastructure/main.tf

fix probate frontend secret from code

---

charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/requirements.yaml

Bumping node chart

---

app/setupSecrets.js
test/unit/testSetupSecrets.js

fix secret mapping

---

app/steps/ui/payment/breakdown/template.html
app/views/widgets/addresslookup.html

N/A
Add BasePath to includes
```
[ ] Yes
[X] No
```

Add BasePath to includes

---

app/views/includes/two_thirds_form.html

N/A
Add id to main form
```
[ ] Yes
[X] No
```

Add id to main form

---

app/setupSecrets.js
charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.preview.template.yaml
charts/probate-caveats-fe/values.yaml

https://tools.hmcts.net/jira/browse/PRO-7290
Add GA Tracking Id secret
```
[ ] Yes
[X] No
```

PRO-7290: Add GA Tracking Id secret

---

config/default.yaml

https://tools.hmcts.net/jira/browse/PRO-7290
Replace default value for localhost
```
[ ] Yes
[X] No
```

PRO-7290: Change default GA Id for localhost

---

.gitignore
README.md
app.js
app/featureToggles.js
app/setupSecrets.js
app/shutter.js
app/utils/FeatureToggle.js
charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/requirements.yaml
charts/probate-caveats-fe/values.preview.template.yaml
charts/probate-caveats-fe/values.yaml
config/custom-environment-variables.yaml
config/default.yaml
config/dev_template.yaml
package.json
test/accessibility/a11yTest.js
test/component/testShutterPage.js
test/data/launchdarkly/simple_flag_data.yaml
test/unit/testFeatureToggle.js
test/util/TestWrapper.js
yarn.lock

https://tools.hmcts.net/jira/browse/PRO-7220
Implement LaunchDarkly and fix some component tests.
```
[ ] Yes
[X] No
```

PRO-7220: Implement LaunchDarkly

---

app/resources/cy/translation/common.json
app/resources/en/translation/common.json

https://tools.hmcts.net/jira/browse/PRO-7200
Add GOV.UK suffix to page titles
```
[ ] Yes
[X] No
```

PRO-7200: Add GOV.UK suffix to page titles

---

app/steps/ui/applicant/address/template.html
app/steps/ui/deceased/address/template.html
app/views/widgets/addresslookup.html
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PRO-7207
Fix bug with Address form not expanding on IE and Edge when address picked from dropdown menu
```
[ ] Yes
[X] No
```

PRO-7207: Fix address form on IE

---

app.js

https://tools.hmcts.net/jira/browse/PRO-7313
Add Google Tag Manager to Content Security Policy whitelisting
```
[ ] Yes
[X] No
```

PRO-7313: Add Google Tag Manager to CSP

---

app.js

https://tools.hmcts.net/jira/browse/PRO-7313
Add Google Tag Manager to Content Security Policy whitelisting
```
[ ] Yes
[X] No
```

PRO-7313: Add Google Analytics to images CSP

---

app.js

https://tools.hmcts.net/jira/browse/PRO-7313
Add Google Tag Manager to Content Security Policy whitelisting
```
[ ] Yes
[X] No
```

PRO-7313: Add stats.g.doubleclick.net to images CSP

---

app/core/steps/DateStep.js
app/core/steps/Step.js
app/core/steps/ValidationStep.js
app/resources/cy/translation/deceased/dob.json
app/resources/cy/translation/deceased/dod.json
app/resources/en/translation/deceased/dob.json
app/resources/en/translation/deceased/dod.json

https://tools.hmcts.net/jira/browse/PRO-7210
Only show 1 error for missing date instead of 3 (day, month and year)
```
[ ] Yes
[X] No
```

PRO-7210: Date Error Messages

---

app/resources/cy/translation/addAlias.json
app/resources/cy/translation/applicant/address.json
app/resources/cy/translation/applicant/email.json
app/resources/cy/translation/applicant/name.json
app/resources/cy/translation/deceased/address.json
app/resources/cy/translation/deceased/dob.json
app/resources/cy/translation/deceased/dod.json
app/resources/cy/translation/deceased/name.json
app/resources/cy/translation/deceased/othernames.json
app/resources/cy/translation/removeAlias.json

https://tools.hmcts.net/jira/browse/PRO-7201
Add Welsh translations
```
[ ] Yes
[X] No
```

PRO-7201: Add Welsh translations

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PRO-7373
Update webchat dependency
```
[ ] Yes
[X] No
```

PRO-7373: Update webchat dependency

---

app/components/submit-data.js
app/middleware/completeEqualityTask.js
test/unit/middleware/testCompleteEqualityTask.js

Remove PCQ ID if PCQ is down.
```
[ ] Yes
[ ] No
```

Remove PCQ ID if PCQ is down

---

app.js

Force build
```
[ ] Yes
[ ] No
```

Trivial change to force build

---

app/views/includes/error_summary.html
app/views/includes/scripts_ga_1.html

Relates to
https://tools.hmcts.net/jira/browse/PRO-7428
```
[ ] Yes
[ ] No
```

adding data layer tag

---

app/core/steps/Step.js
app/views/includes/help_details.html
app/views/includes/scripts.html
charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/requirements.yaml

Hide webchat on Welsh
```
[ ] Yes
[X] No
```

Hide webchat on Welsh

---

charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.yaml

https://tools.hmcts.net/jira/browse/PCQ-273
Chart changes for PCQ-273 - PR #279: Add pcq token key to secret list.
```
[ ] Yes
[x] No
```

PCQ-273: Chart changes

---

charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.yaml

https://tools.hmcts.net/jira/browse/PRO-7681
reverting  chart version and orch url
```
[ ] Yes
[X ] No
```

PRO-7681 reverting chart version and orch url

---

Jenkinsfile_CNP

PRO-7880: remove installCharts

---

Jenkinsfile_CNP

PRO-7880: fix build again for fee code

---

app/core/initSteps.js
app/routes.js

fix for crashing app

---

charts/probate-caveats-fe/values.aat.template.yaml
charts/probate-caveats-fe/values.preview.template.yaml
config/custom-environment-variables.yaml
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-515
Added explicit variable for launch darkly enablement so that it could be switched off in perftest.
```
[ ] Yes
[ X ] No
```

DTSPB-515 env var for launch darkly

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/DTSPB-607
Updated the common component for secrets in the jenkins cnp file to pick up the nightly builds
```
[ ] Yes
[ X ] No
```

DTSPB-607 Updated Jenkins cnp file for the nightly builds

---

app/healthcheck.js
test/unit/utils/testHealthcheck.js

https://tools.hmcts.net/jira/browse/DTSPB-552
remove pcq health check and pcq health check tests
```
[ ] Yes
[x] No
```

remove pcq health check and pcq health check tests

---

bin/run-functional-tests.sh
config/testing.yaml
test/end-to-end/config.js

https://tools.hmcts.net/jira/browse/DTSPB-958
```
[ ] Yes
[X ] No
```

DTSPB-958-CavetE2E-Tests fix

---

config/testing.yaml
test/end-to-end/config.js
test/end-to-end/paths/caveat.stop.and.continue.e2e.js
test/end-to-end/paths/caveatstopAndContinue.e2e.js
test/end-to-end/saucelabs.conf.js

https://tools.hmcts.net/jira/browse/DTSPB-973
Caveat Stop and continue Main applicant E2E Test
```
[ ] Yes
[ X] No
```

Dtspb 973 caveat stop and continue e2 e

---

app/healthcheck.js

DTSPB-976
caveat health endpoint
```
[ ] Yes
[x] No
```

fixing the router journey

---

Jenkinsfile_nightly
bin/run-nightly-functional-tests.sh
package.json
test/accessibility/a11yTest.js

https://tools.hmcts.net/jira/browse/DTSPB-1036
Caveat FE Welsh Accessibility Tests
Caveat FE Welsh Accessibility Tests
```
[ ] Yes
[X ] No
```

DTSPB1036-Welsh AccessbilityTests

---

app/resources/cy/translation/common.json
app/resources/en/translation/common.json
config/testing.yaml
test/end-to-end/config.js

DTSPB-1210: change the operating hours
DTSPB-1210: change the operating hours
```
[ ] Yes
[x] No
```

DTSPB-1210: change the operating hours

---

app/utils/FeesLookup.js
test/unit/testFeesLookup.js

hardcoded to use new keyword
hardcoded to use new keyword
```
[ ] Yes
[x] No
```

Caveat to use new keyword without feature toggle

---

app/utils/FeesLookup.js

DTSPB-1389: adding logging to check why keyword failed in AAT
DTSPB-1389: adding logging to check why keyword failed in AAT
```
[ ] Yes
[x] No
```

DTSPB-1389: adding logging to check why keyword failed in AAT

---

.github/renovate.json
app.js

DTSPB-1408
Update missing readiness and renovate.json
Update missing readiness and renovate.json
```
[ ] Yes
[x] No
```

adding /health/readiness

---

app/steps/ui/static/contact/template.html

DTPSB-1264: adding Webchat details into the contact us page
DTPSB-1264: adding Webchat details into the contact us page
```
[ ] Yes
[x] No
```

DTPSB-1264: adding Webchat details into the contact us page

---

charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.aat.template.yaml
charts/probate-caveats-fe/values.preview.template.yaml
charts/probate-caveats-fe/values.yaml

DTSBP-1256 - upgrade the chart version and adding launchdarkly user key
change the aat feature toggle to true
```
[ ] Yes
[x] No
```

upgrade chart.yaml and adding launchdarkly user key

---

test/end-to-end/codecept.conf.js

- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ ] No
```

DTSPB-1412 Remove the proxy  config

---

app/assets/javascripts/avaya-webchat.js
app/resources/cy/translation/common.json
app/resources/en/translation/common.json
app/views/includes/avaya-webchat.html

adding mainteance message
adding mainteance message
```
[ ] Yes
[x] No
```

adding mainteance message

---

app/views/includes/scripts.html

DTSPB-2027: update webhat sha value
DTSPB-2027: update webhat sha value
```
[ ] Yes
[x] No
```

DTSPB-2027: update webhat sha value

---

Jenkinsfile_CNP

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPB-2020
Change description
code changes to sync all branches to master with every deployment
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X ] No

DTSPB-2020 Sync All branches to master with every build

---

sonar-project.properties

This PR will help in creation of a dashboard as currently there is no consistency between sonar project names.
```
[ ] Yes
[X] No
```

Normalising sonar project name

---

package.json

Normalise sonar project name in package.json

---

test/end-to-end/saucelabs.conf.js

DTSPB-2283: remove tunnelIdentifier
DTSPB-2283: remove tunnelIdentifier
```
[ ] Yes
[x] No
```

DTSPB-2283: remove tunnelIdentifier

---

test/crossbrowser/supportedBrowsers.js

Remove IE X-Browsers from nightly pipeline
```
[ ] Yes
[ X] No
```

Comment the IE Browser from caveats FE nightly

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-2491
Update Volume Dep Version
```
[ ] Yes
[X ] No
```

DTSPB-2491 Update Volume Dep Version

---

Jenkinsfile_CNP
Jenkinsfile_nightly

Change yarn invocation as advised by platops

---

charts/probate-caveats-fe/values.aat.template.yaml

add PCQ URL to staging conf for nightly values.aat.template.yaml

---

app/resources/cy/translation/applicant/address.json
app/resources/en/translation/applicant/address.json

DTSPB-2181: fix caveat wording

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-2675
minimist dependency warning
```
[ ] Yes
[ ] No
```

DTSPB-2676: minimist dependency warning

---

yarn.lock

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPB-2730
Change description
fix dep issue
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ ] No

DTSPB-2730 fix async dep issue

---

.github/renovate.json

DTSPB-2792
Update renovate.json so run weekly creates single PR - matched probate-frontend renovate.json
```
[ ] Yes
[x] No
```

Update renovate so run weekly creates single PR

---

charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.preview.template.yaml
charts/probate-caveats-fe/values.yaml

DTSPB-2888
Copy PR https://github.com/hmcts/probate-frontend/pull/1679/
```
[ ] Yes
[ ] No
```

Copy PR https://github.com/hmcts/probate-frontend/pull/1679/

---

sonar-project.properties

https://tools.hmcts.net/jira/browse/DTSPB-2912
Suppress sonar warning
```
[ ] Yes
[ ] No
```

DTSPB-2912: suppress sonar

---

charts/probate-caveats-fe/Chart.yaml
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-2949
file-type dep issue
```
[ ] Yes
[x] No
```

DTSPB-2949 update file-type

---

charts/probate-caveats-fe/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2943
Upgarde chart nodejs
```
[ ] Yes
[x] No
```

DTSPB-2943 - upgarde node js

---

config/default.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2948
increase health timeout
```
[ ] Yes
[x] No
```

DTSPB-2948 increase health timeout

---

app/assets/javascripts/avaya-webchat-1.js

https://tools.hmcts.net/jira/browse/DTSPB-2977
revert ewt changes
```
[ ] Yes
[x] No
```

DTSPB-2977 Revert EWT changes

---

sonar-project.properties

https://tools.hmcts.net/jira/browse/DTSPB-2913
Fix sonar config
```
[ ] Yes
[ ] No
```

DTSPB-2913: fix sonar config

---

charts/probate-caveats-fe/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSSE-2755

Fix failing chart

---

charts/probate-caveats-fe/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSSE-2784
```
[ ] Yes
[ ] No
```

New chart released for DNS update in Demo

---

Jenkinsfile_nightly

DTSPB-3321
```
[ ] Yes
[x] No
```

DTSPB-3321 fix after to afterAlways

---

README.md
app/components/security.js
app/setupSecrets.js
app/steps/ui/payment/breakdown/index.js
config/dev-aat.yaml
package.json
test/unit/testSetupSecrets.js

https://tools.hmcts.net/jira/browse/DTSPB-3310
```
[ ] Yes
[x] No
```

pointing caveats frontend to aat based off DTSPB-3276

---

README.md
bin/run-functional-tests.sh

Functional test fix for staging env

---

charts/probate-caveats-fe/Chart.yaml

DTSPB-3341
```
[ ] Yes
[x] No
```

DTSPB-3341

---

app/assets/sass/application-ie8.scss
app/assets/sass/application.scss
app/resources/cy/translation/common.json
app/resources/en/translation/common.json
app/steps/ui/thankyou/template.html
app/views/errors/error.html
app/views/includes/layout.html

https://tools.hmcts.net/jira/browse/DTSPB-3588
```
[ ] Yes
[x] No
```

DTSPB-3588 update Exit survey Link

---

app/resources/cy/translation/common.json
app/resources/en/translation/common.json
app/steps/ui/thankyou/template.html
app/views/errors/error.html
app/views/includes/layout.html

https://tools.hmcts.net/jira/browse/DTSPB-3588
Exit survey changes
```
[ ] Yes
[X] No
```

DTSPB-3588 Update survey link changes

---

app/resources/cy/translation/common.json

https://tools.hmcts.net/jira/browse/DTSPB-3691
```
[ ] Yes
[x ] No
```

DTSPB-3691 added walesh translation on exit survey link .

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/DTSPB-3760
```
[ ] Yes
[x ] No
```

DTSPB-3760 update renovate config 

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-3841

DTSPB-3841 Fix CVE

---

app/setupSecrets.js
charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.preview.template.yaml
charts/probate-caveats-fe/values.yaml
config/custom-environment-variables.yaml
config/default.yaml
docker-compose.yml
package.json
server.js
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-3908

DTSPB-3908 AppInsight Connection String

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-4114

DTSPB-4114 updated the express package

---

charts/probate-caveats-fe/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-4118

DTSPB-4118 new chart version for enabling hpa

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-4155

DTSPB-4155 Fix CVE

---

Jenkinsfile_nightly

[DTSPB-4194](https://tools.hmcts.net/jira/browse/DTSPB-4194)

DTSPB-4194 change nightly execution time

---

package.json
yarn.lock

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

DTSPB-4420: Resolved CVE by adding import-in-the-middle

---

test/contract/pact/external/PaymentClient.spec.js

See [DTSPB-4058](https://tools.hmcts.net/jira/browse/DTSPB-4058)
Referencing implementation in [ccpay's CardPaymentProviderTest.java](https://github.com/hmcts/ccpay-payment-app/blob/c6421dbc63d1f3cc3f3baace84f169cde03a3086/api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java#L237) change these values so we match what they provide.
This seems backwards, but I guess gets us validating hopefully.

DTSPB-4058 Update expectations to match what provider seems to actually do

---

charts/probate-caveats-fe/Chart.yaml

Reverts hmcts/probate-caveats-frontend#1022

Revert "Update Helm release redis to v20.4.0"

---

app/utils/getContentSecurityPolicy.js
app/views/includes/scripts.html

DTSPB-4099
fix CSP and js error

DTSPB-4099 fix CSP and js error

---

charts/probate-caveats-fe/Chart.yaml

resolves DTSPB-4586 https://tools.hmcts.net/jira/browse/DTSPB-4586

DTSPB-4586 update node helm url to use oci

---

package.json
yarn.lock

DTSPB-4649 Fix CVE

---

app/views/includes/error_summary.html

Resolves: https://tools.hmcts.net/jira/browse/DTSPB-4460

add aria label to error summary

---

charts/probate-caveats-fe/Chart.yaml
charts/probate-caveats-fe/values.preview.template.yaml
docker-compose.yml

https://tools.hmcts.net/jira/browse/DTSPB-4695

DTSPB-4695 Move over to OCI repository for helm charts - 2nd round

---

test/java/build.gradle

See [DTSPB-4761](https://tools.hmcts.net/jira/browse/DTSPB-4761)
Remove jitpack from gradle config, add azure.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

DTSPB-4761 migrate away from jitpack.

---

app/resources/cy/translation/static/privacy.json
app/resources/en/translation/static/privacy.json

https://tools.hmcts.net/jira/browse/DTSPB-4490
Need to be tested on preview
NA
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

DTSPB-4490 Updated Privacy policy from 90 to 180 days

---

yarn.lock

Reverts hmcts/probate-caveats-frontend#1361

Revert "Update dependency codeceptjs to v3.7.4"
